### ISSUE TITLE
\answer[inline]{}

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/ximeraLatex#13]
\answer[inline]{----}

What this would do is make standard answer blanks online, but on paper, it would make a box (or an underline) that would be based on the size of the actual answer. Hence you could easily write "fill-in-the-blank" worksheets.

**Comment by sahenke** [comment]
How about a separate function \inlineanswer[width]{#1}?  This would let us have different options for inline answers, and would make it easy to redefine to get different behavior without affecting the regular answer command.  I would make the default width some multiple of the natural width, because handwriting will take a bit more space than typesetting.  This could be accomplished by something like

\setbox0=\hbox{#1}
\underline{\hbox to factor*\wd0{\hfil}}

to create an underline or

\setbox0=\hbox{#1}
\fbox to factor*\wd0{\hfil}

**Comment by bartsnapp** [comment]
We could use this

http://tex.stackexchange.com/questions/18576/get-width-of-a-given-text-as-length

**Comment by bartsnapp** [comment]
This can be done with a custom .sty file
