### ISSUE TITLE
\sage{my_var} does not work

### ISSUE THREAD

**Issue by oguzkurt** [XimeraProject/ximeraLatex#78]
Hi folks,

I have given a break to using ximera since last meeting due to busy schedule. I am uploading my files to the new system. I came to realize some of the parts such as `\answer{\sage{my_var}}` and `\sage{my_var}` does not work properly. Here, `my_var` comes from within `sagesilent`.  Instead it gives this image which suggests that it is uploading the info (dots rotating clockwise on a circle).

Any idea how to overcome it?

Best,
Oguz

**Comment by kisonecat** [comment]
Can you share the whole file?  I can dig into it more easily that way.

**Comment by oguzkurt** [comment]
actually, whole file is added to ximera already. If you fix one of them, I
can probably fix all of them :) HEre you go!

https://ximera.osu.edu/oguzkurt/StatisticsCourse/StatisticsCourse/StatisticsCourse/hw/hw1.tex

**Comment by Zengez** [comment]
This behavior happens when sage itself fails to resolve, for example sage encounters an internal error (eg divide by 0 error) or an unrecognized command (eg if you type radnom instead of random by accident). This is a little annoying as there isn't really any visual indication that there was a problem, but if you inspect element on the problem there is usually a sage error buried in the resulting info that comes up if you look hard enough.
~Jason

**Comment by Zengez** [comment]
Indeed, going to the referenced site (minus the .tex extension) and looking at the inspect code reveals:
"NameError"
evalue
:
"name 'data' is not defined"

Not sure why this is true since I see that you have a vector 'data', but nonetheless that is the source of the problem, if it helps.

**Comment by oguzkurt** [comment]
Ooops! I did use auto-indentation future to make my file look nicer. Except
that auto-indentation cannot recognize a sage code within latex and so it
flattened everything in sagesilent environment. Funny!
I will fix it and update you on that.
