### ISSUE TITLE
Example files deleted but referred to in README.md

### ISSUE THREAD

**Issue by mitchkeller** [XimeraProject/ximeraLatex#83]
Commit 2ba6b64c6 seems to have deleted all the example files referred to in README.md. Since that appears to be all that commit did, I'm interpreting that as intentional. However, (a) it seems odd to not have examples included in the bundle and (b) it's even more odd that the README still replies to those files as a way to test that ximeraLatex is installed properly.

**Comment by bartsnapp** [comment]
Thanks for pointing this out, I see what you mean.

I'll get this cleaned up tomorrow.

All the best,
-Bart

On Aug 10, 2018 6:24 PM, "Mitchel T. Keller" <notifications@github.com>
wrote:

Commit 2ba6b64
<https://github.com/XimeraProject/ximeraLatex/commit/2ba6b64c600de1509d50f705dcb5d5c8707d8ac0>
seems to have deleted all the example files referred to in README.md. Since
that appears to be all that commit did, I'm interpreting that as
intentional. However, (a) it seems odd to not have examples included in the
bundle and (b) it's even more odd that the README still replies to those
files as a way to test that ximeraLatex is installed properly.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/XimeraProject/ximeraLatex/issues/83>, or mute the thread

**Comment by bartsnapp** [comment]
Ok! I've moved much of the info there to 

https://ximera.osu.edu/introduction/gettingStarted

and there are other example files here:

https://ximera.osu.edu/introduction/examples
